Repository dabin-Hailey/IKUZO-WIKI, pull requests merged in 2023-09, with the labels that each got.

#7 Feature/#6
  package.json
  src/assets/headerIcon.svg
  src/components/common/Header/Header.css
  src/components/common/Header/Heager.css
  src/components/common/Header/index.tsx
  src/index.css
  src/pages/Home.tsx
  src/pages/Wiki.tsx
Labels: newComponent

#17 Feature/#15
  package-lock.json
  package.json
  src/assets/sidebar.svg
  src/components/common/SidebarGallery/SidebarGallery.css
  src/components/common/SidebarGallery/index.tsx
  src/components/common/SidebarWiki/Sidebar.css
  src/components/common/SidebarWiki/index.tsx
Labels: documentation

#24 Feature/#23
  .eslintrc.json
  src/components/wiki/With/Modal/index.tsx
  src/components/wiki/With/index.tsx
Labels: newComponent

#29 Feature/#13
  src/assets/galleryDeleteIcon.svg
  src/assets/galleryReplaceIcon.svg
  src/components/gallery/GalleryItems.tsx
  src/components/gallery/GalleryListing.tsx
  src/components/gallery/Modal/GalleryModal.tsx
  src/components/gallery/Modal/Modal.css
  src/components/gallery/index.tsx
  src/pages/Chinese.tsx
  src/pages/Gallery.tsx
  src/pages/Japanese.tsx
  src/pages/Korean.tsx
  src/pages/Western.tsx
Labels: enhancement

#28 Feature/#26
  src/components/wiki/With/WIthItem/index.tsx
  src/components/wiki/With/WithTime/index.tsx
  src/pages/With.tsx
  src/utils/util.tsx
Labels: enhancement

#31 Fix: 모집 시간 버튼으로 변경 및 db 저장값 변경, modal 버튼 위치 변경
  src/components/wiki/With/Modal/index.tsx
  src/components/wiki/With/index.tsx
Labels: enhancement

#51 Fix: map 페이지 TypeError 수정
  src/components/map/index.tsx
Labels: bug

#55 Feat: 같이먹을사람 구해요 모달에 지도 추가
  src/components/map/index.tsx
  src/components/wiki/With/Modal/index.tsx
  src/components/wiki/With/index.tsx
Labels: newComponent

#57 Fix: Map 페이지 삭제 및 라우팅 해제
  src/App.tsx
  src/components/map/index.tsx
  src/components/wiki/With/Modal/index.tsx
  src/pages/Map.tsx
Labels: bug

#71 Feat: pagnation 기능 추가
  package-lock.json
  package.json
  src/components/gallery/Pagination/index.tsx
  src/components/gallery/index.tsx
Labels: newComponent

#77 Feat: 갤러리 모달 버튼 중복클릭 방지기능 추가 및 불필요한 파일 삭제
  src/components/common/SidebarGallery/AddModal.tsx
  src/components/gallery/Modal/UpdateModal.tsx
  src/components/wiki/Modal/index.tsx
  src/pages/Gallery.tsx
  src/pages/Wiki.tsx
Labels: newComponent

#79 Feat: 마커 및 식당 목록 아이템 클릭시 확대 & 지도 이동
  src/components/map/index.tsx
Labels: newComponent

#84 Feature/#73
  package-lock.json
  package.json
  src/App.tsx
  src/components/chooseid/ChooseEmailButton.tsx
  src/components/chooseid/index.tsx
  src/components/common/Header/LoginBtn.tsx
  src/components/login/index.tsx
  src/components/register/index.tsx
  src/hooks/getAuth.ts
  src/hooks/getLoginAuth.ts
  src/hooks/getStorageAuthData.ts
  src/pages/ChooseId.tsx
  src/pages/Register.tsx
  src/recoil/authRecoil.ts
  src/recoil/countRecoil.ts
Labels: enhancement

#94 Fix: Received false for a non-boolean attribute transparent 에러 해결
  src/components/common/Header/index.tsx
  src/components/common/Layout/GalleryLayout.tsx
  src/components/common/Layout/WikiLayout.tsx
  src/components/home/index.tsx
  src/pages/Login.tsx
Labels: bug

#99 Style: 주석 제거 및 제목 변경
  src/components/common/Header/index.tsx
  src/components/common/Layout/Layout.tsx
  src/components/home/index.tsx
  src/components/map/index.tsx
  src/components/markdown/Markdown.styled.tsx
  src/components/markdown/MarkdownEditor.tsx
  src/components/markdown/MarkdownViewer.tsx
Labels: documentation

#102 Feature/#101
  README.md
  src/utils/util.tsx
Labels: bug

#108 Feature/#107
  src/components/wiki/With/Modal/index.tsx
  src/components/wiki/With/WithButton/index.tsx
  src/utils/util.tsx
Labels: bug

#111 Fix: map component any type 제거
  src/components/map/index.tsx
Labels: enhancement

#119 Feat: 이미지 업로드 크기 제한
  src/components/common/SidebarGallery/AddModal.tsx
  src/components/gallery/Modal/UpdateModal.tsx
Labels: enhancement
